# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] 
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: SSH 설정
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}
    - name: EC2애 파일 복사해넣기
      run: |
        scp -r -o StrictHostKeyChecking=no ./* ubuntu@${{ secrets.HOST }}:/home/ubuntu/frontend/docker_front
    - name: npm 패키지 설치
      run: npm install
    - name: 사용자를 Docker그룹에 추가
      run: |
        sudo usermod -aG docker $USER
    - name: 도커 세션 로드하기
      run: |
        sudo chmod 666 /var/run/docker.sock
    - name: 셀상의 EC2 그리고 도커 compose 실행
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} << 'EOF'
          # 여러 줄의 명령어를 SSH를 통해 원격으로 EC2 서버에 전송할 수 있게 한다. EOF로 끝을 알려준다.
          cd /home/ubuntu/frontend/docker_front
          docker-compose down
          docker-compose up -d --build
        EOF
